query GetPost($id: ID!) {
	post(id: $id) {
		id
		title
		content
		author {
			id
			firstName
			lastName
		}
		comments {
			id
			comment
			author {
				id
				firstName
				lastName
			}
		}
	}
}
